name: 'Dotnet Pack & Push'
description: 'Packages the project into a NuGet file and pushes it to the gallery'

inputs:
  configuration:
    description: 'Build configuration (Release/Debug)'
    required: true
    default: 'Debug'
  version_suffix:
    description: 'Optional suffix for prerelease versions (e.g., ci-123)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Pack NuGet Package
      shell: bash
      run: |
        dotnet pack --configuration ${{ inputs.configuration }} --no-build -o ./dist \
        ${{ inputs.version_suffix && format('--version-suffix {0}', inputs.version_suffix) || '' }}

    - name: Get NuGet OIDC token
      id: nuget-login
      uses: NuGet/login@v1

    - name: Push to NuGet.org
      shell: bash
      run: |
        dotnet nuget push "./dist/*.nupkg" \
          --api-key ${{ steps.nuget-login.outputs.api-key }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate