name: 'Dotnet Pack & Push'
description: 'Packages the project into a NuGet file and pushes it to the gallery'

inputs:
  configuration:
    description: 'Build configuration (Release/Debug)'
    required: true
    default: 'Release'
  version_suffix:
    description: 'Optional suffix for prerelease versions (e.g., ci-123)'
    required: false
  nuget_key:
    description: 'The NuGet.org API Key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Pack NuGet Package
      shell: bash
      # If version_suffix is provided, it appends it (e.g., 1.0.0-ci-123)
      # If not, it builds a stable version (e.g., 1.0.0)
      run: |
        dotnet pack --configuration ${{ inputs.configuration }} -o ./dist \
        ${{ inputs.version_suffix && format('--version-suffix {0}', inputs.version_suffix) || '' }}

    - name: Push to NuGet.org
      shell: bash
      # --skip-duplicate ensures that if you re-run a tag, it doesn't crash the pipeline
      run: |
        dotnet nuget push "./dist/*.nupkg" \
          --api-key ${{ inputs.nuget_key }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate