# .github/actions/setup/action.yml
name: 'Setup'
description: 'Prepares SDK, Updates Packages, and Restores'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/global.json', '**/*.csproj') }}

    - name: Restore
      shell: bash
      run: |
        dotnet restore